#!/bin/bash
file_check() {
    if [ ! -d $1 ]; then 
        echo ' il faut un fichier csv'
        return 1
    fi 
    var=$1
    if [ ! "${var##*.}" = "csv" ]; then

        echo " the argument must be a csv file"
        return 1
    fi
    #verif nombre de colonne
    return 0


}
#trait_argument() {
 #if [ "$6" = "1" ]; then
  #  if [ "$2" = "1" && $5 -ne 0 ];then
   #     cut -d, -f1,2,14,15 $1 > station_height.csv #faut je check si c est virgule ou point virgule
    #    file="station_height.csv"
     #   trait_argument_d_country $file $3 $4 $5 ;
    #elif [ "$2" = "1" && "$5" = "0" ]; then
     #   cut -d, -f1,2,14 $1 > station_height.csv
#}

trait_argument_d_country() {
    file=$1

    if [ $2 -eq 1 ]; then
        #cut les dates
        #créer un fichier
        hello=1
    fi
    case $2 in 

        1) #cut en fonction de fr
        ;;
        2)
        ;;
        3)
        ;;
        4)
        ;;
        5)
        ;;
        6)
        ;;
        *)
        ;;
    esac


}





    x=0
    choice1=0
    choice2=0
    count=0
    for k in $@; do

        if [ $after -eq 1 ]; then 
            if file_check $k; then
             head -1 $k | sed 's/.*/\U&/' | sed -e "s/ //g" > check_field.csv #probleme $1 pas forcement fichier
             file=$k
             check=1
             break;
            else
             echo " the file is not good "
             exit 1
            fi

        fi
        if [ "$k" = "-f" ]; then
            after=1
            
        fi
    done
    if [ $check -ne 1 ]; then
        echo "you forgot the option -f or the file is not good"
        exit 1
    fi
    
     while getopts "t:p:wmhf:FGSAOQd:-:" option
       do
               
               case $option in
                    #file
                    f)  
                    ;;
                    #height
                    h) if [ ! $(grep -x ALTITUDE check_field.csv) ]; then
                            echo "the field altitude don't exist"
                            h=0;
                        else
                            h=1
                            count=$count+1; #permet de vérifier à la fin que au moins un tris est possible
                        fi
                        
                    ;;if [ ! $(grep )]   m) if [ ! $(grep -x HUMIDITÉ check_field.csv) ]; then
                            echo "the field humidité don't exist"
                            m=0;
                        else
                            m=1
                            count=$count+1;
                        fi
                        
                    ;;
                    #wind
                    w) if [ ! $(grep DIRECTIONDUVENTMOYEN10MN check_field.csv) ] || [ ! $(grep VITESSEDUVENTMOYEN10MN check_field.csv) ] ; then
                            echo "the field humidité don't exist"
                            w=0;
                        else
                            w=1
                            count=$count+1;
                        fi
                    ;;
                    #pressure
                    p) if [ "$OPTARG" != "1" ] && [ "$OPTARG" != "2" ] && [ "$OPTARG" != "3"  ]; then
                            echo"p option argument must be 1 2 or 3"
                            exit 1
                        fi
                        
                        # if [ ! $(grep )] #choisir les champs 
                        if [ "$OPTARG" = "1" ]; then
                        p=1
                        count=$count+1;
                        elif [ "$OPTARG" = "2" ]; then
                        p=2           
                        count=$count+1;             
                        else 
                        count=$count+1
                        p=3;                        
                        fi
                    ;;
                    #temperature
                    t) if [ "$OPTARG" != "1" ] && [ "$OPTARG" != "2" ] && [ "$OPTARG" != "3"  ]; then
                            echo"t option argument must be 1 2 or 3"
                            exit 1
                        fi
                        if [ "$OPTARG" = "1" ]; then
                        t=1;
                        elif [ "$OPTARG" = "2" ]; then
                        t=2;                        
                        else 
                        t=3;                        
                        fi
                    ;;
                    -) case $OPTARG in 
                          avl) avl=1 #avl
                            ;;
                            abr) abr=1 #abr
                           ;;
                            tab) tab=1 #list
                            ;;
                           help) help=1 #help
                            ;;
                            *) echo"-- option argument must be avl, abr, help or tab"
                            exit 1
                            ;;
                        esac
                    ;;

                    F) if [ $x -ne 0 ]; then
                            echo "you need to choose only one location"
                            exit 1
                        fi
                        x=1
                    ;;
                    G)  if [ $x -ne 0 ]; then
                            echo "you need to choose only one location"
                            exit 1
                        fi
                        x=2
                    ;;
                    S)  if [ $x -ne 0 ]; then
                            echo "you need to choose only one location"
                            exit 1
                        fi
                        x=3
                    ;;
                    A)  if [ $x -ne 0 ]; then
                            echo "you need to choose only one location"
                            exit 1
                        fi
                        x=4
                    ;;
                    O)  if [ $x -ne 0 ]; then
                            echo "you need to choose only one location"
                            exit 1
                        fi
                        x=5
                    ;;
                    Q)  if [ $x -ne 0 ]; then
                            echo "you need to choose only one location"
                            exit 1
                        fi
                        x=6
                    ;;
                    d)
                        begin=$(date -d "2010/01/01" +%s)
                        finish=$(date -d "2021/12/31" +%s)
                        choice=$OPTARG
                        choice1=${choice%%,*}
                        choice2=${choice#*,}
                        echo "$choice1 $choice2"
                        choice1=$(date -d "$choice1" +%s) 
                        choice2=$(date -d "$choice2" +%s)#faire un exit si mauvaise date
                          
                        if [ $choice1 -gt $choice2 ] || [ $choice1 -lt $begin ] || [ $choice1 -gt $finish ] || [ $choice2 -lt $begin ] || [ $choice2 -gt $finish  ]; then
                            echo " you can't choose a date before the 2010/01/01 and after the 2021/12/31 and the first date must be the smallest"
                        fi 
                        d=1
                        ;;
                        *) 
                        ;;
                esac
            done
            echo "5"
            #trait_argument $file $d $choice1 $choice2 $x $h $m $w $p $t
